import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const currencies={INR:{symbol:'₹',rate:1,name:'Indian Rupee'},USD:{symbol:'$',rate:.0119,name:'US Dollar'},GBP:{symbol:'£',rate:.0088,name:'British Pound'},EUR:{symbol:'€',rate:.0101,name:'Euro'},AED:{symbol:'د.إ',rate:.0437,name:'UAE Dirham'},SAR:{symbol:'﷼',rate:.0446,name:'Saudi Riyal'},CAD:{symbol:'C$',rate:.0161,name:'Canadian Dollar'},AUD:{symbol:'A$',rate:.0177,name:'Australian Dollar'}};
const KEY='mahek-sadia-books-v3';
const starter=[{id:'darmiyan',title:'درمیان',roman:'Darmiyan',author:'مہک سعدیہ',price:199,genre:'Urdu Novel',language:'Urdu',description:'ایک ایسی کہانی جو انسان کو دوسروں میں نہیں، اپنے اندر تلاش کرنے پر مجبور کرے۔',cover:'✦',ebook:null,featured:true}];
function readBooks(){try{return JSON.parse(localStorage.getItem(KEY))||starter}catch{return starter}}
function writeBooks(b){localStorage.setItem(KEY,JSON.stringify(b.filter(x=>!x.ebook||typeof x.ebook==='string')))}
function money(inr,c){const x=inr*currencies[c].rate;return currencies[c].symbol+(c==='INR'?Math.round(x):x.toFixed(2))}
function App(){
 const [books,setBooks]=useState(readBooks),[currency,setCurrency]=useState('INR'),[adminOpen,setAdminOpen]=useState(false),[logged,setLogged]=useState(false),[reader,setReader]=useState(null),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const saved=localStorage.getItem(KEY);if(saved)try{setBooks(JSON.parse(saved))}catch{}},[]);
 const filtered=useMemo(()=>books.filter(b=>(b.title+' '+b.roman+' '+b.genre).toLowerCase().includes(query.toLowerCase())),[books,query]);
 const login=e=>{e.preventDefault(); if(e.currentTarget.password.value==='mahek2026'){setLogged(true);setNotice('Welcome to your admin dashboard.')}else setNotice('Incorrect admin password.')};
 const addBook=e=>{e.preventDefault();const f=e.currentTarget,file=f.pdf.files[0];if(!file||file.type!=='application/pdf')return setNotice('Please select a PDF file.');const r=new FileReader();r.onload=()=>{const b={id:crypto.randomUUID(),title:f.title.value,roman:f.roman.value||f.title.value,author:'مہک سعدیہ',price:Number(f.price.value||0),genre:f.genre.value||'Urdu Novel',language:'Urdu',description:f.description.value||'Digital edition by Mahek Sadia.',cover:'✦',ebook:r.result,featured:false};const next=[...books,b];setBooks(next);localStorage.setItem(KEY,JSON.stringify(next));f.reset();setNotice('Book added to your library.');};r.readAsDataURL(file)};
 const remove=id=>{const next=books.filter(b=>b.id!==id);setBooks(next);localStorage.setItem(KEY,JSON.stringify(next));setNotice('Book removed.')};
 return <div className="app">
 <header><div className="brand"><div className="mark">م</div><div><strong>Mahek Sadia</strong><span>مہک سعدیہ · Digital Bookstore</span></div></div><nav><button onClick={()=>document.getElementById('books').scrollIntoView({behavior:'smooth'})}>Books</button><button onClick={()=>document.getElementById('about').scrollIntoView({behavior:'smooth'})}>About</button></nav><div className="actions"><select value={currency} onChange={e=>setCurrency(e.target.value)}>{Object.entries(currencies).map(([k,v])=><option key={k}>{k} — {v.name}</option>)}</select><button className="adminBtn" onClick={()=>setAdminOpen(true)}>Admin</button></div></header>
 <main><section className="hero"><div className="heroText"><p className="eyebrow">THE OFFICIAL DIGITAL BOOKSTORE</p><h1>Stories that bring<br/><em>you back to yourself.</em></h1><p className="lead">Urdu novels and digital books by <b>Mahek Sadia</b> — written between duniya, deen, emotions and the quiet truths we carry inside.</p><button className="primary" onClick={()=>document.getElementById('books').scrollIntoView({behavior:'smooth'})}>Explore Books <span>→</span></button></div><div className="heroArt"><div className="bookGlow"><span>مہک<br/>سعدیہ</span><small>BOOKS</small></div></div></section>
 <section className="quote"><span>“</span><p>کچھ کہانیاں ختم نہیں ہوتیں،<br/>وہ انسان کے اندر ایک سوال چھوڑ جاتی ہیں۔</p></section>
 <section id="books" className="library"><div className="sectionHead"><div><p className="eyebrow">THE LIBRARY</p><h2>Books by Mahek Sadia</h2></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search books..."/></div></div><div className="grid">{filtered.map(b=><article className="card" key={b.id}><div className="cover"><div className="coverInner"><small>مہک سعدیہ</small><strong>{b.title}</strong><i>{b.roman}</i><span>✦</span></div></div><div className="cardBody"><p className="tag">{b.genre} · {b.language}</p><h3>{b.title}</h3><p>{b.description}</p><div className="cardFoot"><b>{money(b.price,currency)}</b>{b.ebook?<button className="read" onClick={()=>setReader(b)}>Read ebook →</button>:<button className="buy" onClick={()=>setNotice('Payment checkout can be connected next.')}>Buy ebook</button>}</div></div></article>)}</div></section>
 <section id="about" className="about"><div><p className="eyebrow">ABOUT THE AUTHOR</p><h2>Words, written with purpose.</h2></div><p>Mahek Sadia is a software engineer who writes Urdu fiction and poetry. Her stories explore the space between who we are, who people expect us to be, and the person Allah calls us to become.</p></section></main>
 <footer><div><strong>Mahek Sadia</strong><span>مہک سعدیہ</span></div><p>© {new Date().getFullYear()} Mahek Sadia. All rights reserved.</p></footer>
 {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice} <b>×</b></div>}
 {adminOpen&&<div className="overlay"><div className="adminPanel"><button className="close" onClick={()=>setAdminOpen(false)}>×</button>{!logged?<><p className="eyebrow">PRIVATE AREA</p><h2>Admin Login</h2><p className="muted">Manage your bookstore, add ebooks and keep your library updated.</p><form onSubmit={login}><label>Admin password<input name="password" type="password" placeholder="Enter password" required/></label><button className="primary full">Enter Dashboard</button></form></>:<><div className="dashHead"><div><p className="eyebrow">ADMIN DASHBOARD</p><h2>Your Book Library</h2></div><button className="logout" onClick={()=>setLogged(false)}>Log out</button></div><form className="uploadForm" onSubmit={addBook}><h3>Add new ebook</h3><div className="two"><label>Book title<input name="title" required placeholder="مثلاً درمیان"/></label><label>Roman title<input name="roman" placeholder="Darmiyan"/></label></div><div className="two"><label>Price in INR ₹<input name="price" type="number" min="0" required placeholder="199"/></label><label>Genre<input name="genre" placeholder="Urdu Novel"/></label></div><label>Description<textarea name="description" placeholder="Short description..."/></label><label className="file"><span>Choose PDF ebook</span><input name="pdf" type="file" accept="application/pdf" required/></label><button className="primary full">＋ Upload & Add Book</button></form><div className="inventory"><h3>Current books</h3>{books.map(b=><div className="inventoryRow" key={b.id}><div><strong>{b.title}</strong><span>{b.ebook?'PDF uploaded':'Store listing'} · ₹{b.price}</span></div>{b.id!=='darmiyan'&&<button onClick={()=>remove(b.id)}>Delete</button>}</div>)}</div></>}</div></div>}
 {reader&&<div className="reader"><div className="readerTop"><b>{reader.title}</b><button onClick={()=>setReader(null)}>Close ×</button></div><iframe title={reader.title} src={reader.ebook}/></div>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
