import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const currencies={INR:{symbol:'₹',rate:1,name:'Indian Rupee'},USD:{symbol:'$',rate:0.0119,name:'US Dollar'},GBP:{symbol:'£',rate:0.0088,name:'British Pound'},EUR:{symbol:'€',rate:0.0101,name:'Euro'},AED:{symbol:'د.إ',rate:0.0437,name:'UAE Dirham'},SAR:{symbol:'﷼',rate:0.0446,name:'Saudi Riyal'},CAD:{symbol:'C$',rate:0.0161,name:'Canadian Dollar'},AUD:{symbol:'A$',rate:0.0177,name:'Australian Dollar'}};
const starter=[{id:'darmiyan',title:'درمیان',roman:'Darmiyan',author:'مہک سعدیہ',price:199,genre:'Urdu Novel',language:'Urdu',description:'ایک ایسی کہانی جو انسان کو دوسروں میں نہیں، اپنے اندر تلاش کرنے پر مجبور کرے۔',cover:'✦',ebook:null,featured:true}];

function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('mahek-sadia-store',1);r.onupgradeneeded=()=>r.result.createObjectStore('books',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveBook(b){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('books','readwrite');tx.objectStore('books').put(b);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function loadBooks(){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('books','readonly');const r=tx.objectStore('books').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function deleteBook(id){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('books','readwrite');tx.objectStore('books').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function money(inr,c){const x=inr*currencies[c].rate;return currencies[c].symbol+(c==='INR'?Math.round(x):x.toFixed(2))}

function App(){
 const [books,setBooks]=useState(starter),[currency,setCurrency]=useState('INR'),[admin,setAdmin]=useState(false),[reader,setReader]=useState(null),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{loadBooks().then(x=>{if(x.length)setBooks(x)}).catch(()=>{})},[]);
 const filtered=useMemo(()=>books.filter(b=>(b.title+' '+b.roman+' '+b.genre).toLowerCase().includes(query.toLowerCase())),[books,query]);
 const addBook=async(e)=>{e.preventDefault();const f=e.currentTarget;const file=f.pdf.files[0];if(!file||file.type!=='application/pdf'){setNotice('Please select a PDF file.');return}const id=crypto.randomUUID();const b={id,title:f.title.value,roman:f.roman.value||f.title.value,author:'مہک سعدیہ',price:Number(f.price.value||0),genre:f.genre.value||'Urdu Novel',language:'Urdu',description:f.description.value||'Digital edition by Mahek Sadia.',cover:'✦',ebook:{name:file.name,type:file.type,size:file.size,blob:file},featured:false};await saveBook(b);setBooks(await loadBooks());f.reset();setNotice('Book uploaded successfully. It is now available in this browser.');};
 const remove=async(id)=>{await deleteBook(id);setBooks(await loadBooks())};
 return <div className="app">
  <header><div className="brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><div className="mark">م</div><div><strong>Mahek Sadia</strong><span>مہک سعدیہ · Digital Bookstore</span></div></div><nav><button onClick={()=>document.getElementById('books').scrollIntoView({behavior:'smooth'})}>Books</button><button onClick={()=>document.getElementById('about').scrollIntoView({behavior:'smooth'})}>About</button></nav><div className="actions"><select value={currency} onChange={e=>setCurrency(e.target.value)}>{Object.entries(currencies).map(([k,v])=><option key={k} value={k}>{k} — {v.name}</option>)}</select><button className="adminBtn" onClick={()=>setAdmin(true)}>Admin</button></div><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></header>
  {menu&&<div className="mobileNav"><button onClick={()=>document.getElementById('books').scrollIntoView({behavior:'smooth'})}>Books</button><button onClick={()=>document.getElementById('about').scrollIntoView({behavior:'smooth'})}>About</button></div>}
  <main>
   <section className="hero"><div className="heroText"><p className="eyebrow">THE OFFICIAL DIGITAL BOOKSTORE</p><h1>Stories that bring<br/><em>you back to yourself.</em></h1><p className="lead">Urdu novels and digital books by <b>Mahek Sadia</b> — written between duniya, deen, emotions and the quiet truths we carry inside.</p><button className="primary" onClick={()=>document.getElementById('books').scrollIntoView({behavior:'smooth'})}>Explore Books <span>→</span></button></div><div className="heroArt"><div className="bookGlow"><span>مہک<br/>سعدیہ</span><small>BOOKS</small></div></div></section>
   <section className="quote"><span>“</span><p>کچھ کہانیاں ختم نہیں ہوتیں،<br/>وہ انسان کے اندر ایک سوال چھوڑ جاتی ہیں۔</p></section>
   <section id="books" className="library"><div className="sectionHead"><div><p className="eyebrow">THE LIBRARY</p><h2>Books by Mahek Sadia</h2></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search books..."/></div></div><div className="grid">{filtered.map(b=><article className="card" key={b.id}><div className="cover"><div className="coverInner"><small>مہک سعدیہ</small><strong>{b.title}</strong><i>{b.roman}</i><span>✦</span></div></div><div className="cardBody"><p className="tag">{b.genre} · {b.language}</p><h3>{b.title}</h3><p>{b.description}</p><div className="cardFoot"><b>{money(b.price,currency)}</b>{b.ebook?<button className="read" onClick={()=>setReader(b)}>Read ebook →</button>:<button className="buy" onClick={()=>setNotice('Checkout is ready to connect to your payment provider. Upload and reading are active now.')}>Buy ebook</button>}</div></div></article>)}</div></section>
   <section id="about" className="about"><div><p className="eyebrow">ABOUT THE AUTHOR</p><h2>Words, written with purpose.</h2></div><p>Mahek Sadia is a software engineer who writes Urdu fiction and poetry. Her stories explore the space between who we are, who people expect us to be, and the person Allah calls us to become.</p></section>
  </main>
  <footer><div><strong>Mahek Sadia</strong><span>مہک سعدیہ</span></div><p>© {new Date().getFullYear()} Mahek Sadia. All rights reserved.</p></footer>
  {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice} <b>×</b></div>}
  {admin&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setAdmin(false)}>×</button><p className="eyebrow">ADMIN</p><h2>Upload a new ebook</h2><p className="muted">Choose a PDF directly from your device. It is stored in this browser and opens inside the built-in reader.</p><form onSubmit={addBook}><label>Book title<input name="title" required placeholder="مثلاً درمیان"/></label><label>Roman title<input name="roman" placeholder="Darmiyan"/></label><div className="two"><label>Price in INR<input name="price" type="number" min="0" required placeholder="199"/></label><label>Genre<input name="genre" placeholder="Urdu Novel"/></label></div><label>Description<textarea name="description" placeholder="Short description..."/></label><label className="file"><span>PDF file</span><input name="pdf" type="file" accept="application/pdf" required/></label><button className="primary full">Upload ebook</button></form><div className="adminList">{books.filter(x=>x.ebook).map(x=><div key={x.id}><span>{x.title}</span><button onClick={()=>remove(x.id)}>Delete</button></div>)}</div></div></div>}
  {reader&&<div className="reader"><div className="readerTop"><b>{reader.title}</b><button onClick={()=>setReader(null)}>Close ×</button></div><iframe title={reader.title} src={URL.createObjectURL(reader.ebook.blob)} /></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
